CollectionView作成 #3
kusio940/RecommendRecipe pull request #19
Opened 2020-08-28 13:04 UTC by kusio940

## Issue
CollectionView作成 #3
## 変更内容
・navigationController,Tabbar作成
・Tabbar用に各画面のstoryboard作成
・CollectionView作成（各cellに文字と画像を表示、遷移イベント実装）
・R.swift導入
## レビュー依頼内容
・Xcode上でフォルダ構成がアンチパターンとなっていないか
・CollectionViewControllerにコードレビュー（modelとして切り分けた方がいい箇所があるか）

2020-09-01 00:56 UTC, yamataku29 requested changes
いくつかコメントしました！
フォルダ構成などは致命的なものではないので、一旦は大丈夫です👍

2020-09-01 00:56 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +    let cellSideLength:CGFloat = UIScreen.main.bounds.size.width  / 2.0 - 7.5
マジックナンバーはできるだけ避けるのが良いですね💁‍♂️
https://qiita.com/RyoheiHashimoto/items/38ec132bd2852238295e

もしマジックナンバーを使うとすれば、「その数値は何なのか」を示唆するために、値ごとに変数化するのが望ましいです。

e.g.) let viewMergin: CGFloat =  2.0

2020-09-01 00:56 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        collectionView.collectionViewLayout = cellLayout
ここは一つのfunctionとして切り出すのがよいですね。
プログラムは「意味のある最小単位」でカプセル化するのが定石なので、覚えておきましょう💡
https://www.gixo.jp/blog/5914/

2020-09-01 00:56 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        switch indexPath.row {
ここは各Cellをenumとして表現したいですね。
https://qiita.com/hachinobu/items/392c96820588d1c03b0c#%E5%80%A4%E5%9E%8Benumraw-value-enum

2020-09-01 14:38 UTC, kusio940 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        cell.contentView.addSubview(categoryLabel)
この箇所のように、レイアウト調整をするとマジックナンバーが頻出すると思います。
こちらも一つ一つ変数にした方がよいのでしょうか。

2020-09-02 01:19 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        cell.contentView.addSubview(categoryLabel)
はい、基本的には一つ一つ変数にするのがベストです👌
何故かというと、マジックナンバーだと「何故この処理にX(=マジックナンバー)が書かれているのか」の理由を把握することが不可能だからですね。

これを例えば「marginFromParentView」などという変数にしておけば、後から実装する人が「これは親Viewからのマージンなんだな」と理解することができますよね。

これがいわゆる「リーダブル(Readable)」なコードと言えます😌
もちろん、マジックナンバーやそれを格納する変数は少ない方が良いので、具体的な値(=マジックナンバー)を使用せずに済む方法を模索するのもリファクタリングの一つですね💡

2020-09-05 00:50 UTC, yamataku29 requested changes
いくつかコメントいれました🙆‍♂️💡

2020-09-05 00:50 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        self.collectionView!.register(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)
この場合はUICollectionViewController.viewDidLoad()内での定義なので感嘆符でもいいのですが、通常はあまり矯正Unwrappはしない方がよいです🙅‍♂️

guard-let文を用いてOptional-Bindingをするとよいですね👍

```swift
guard let collectionView = collectionView else { return }
```

2020-09-05 00:50 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        imageView.frame = CGRect(x:0, y:0, width:self.cellSideLength, height:self.cellSideLength)
0はCGFloat.zeroまたは省略形で.zeroと定義することも可能ですので、そちらの方がよいでしょう💁‍♂️

2020-09-05 00:50 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +            $0.removeFromSuperview()
$0でも問題ないのですが、できれば変数名を与えてあげるとよいですね👍

```swift
cell.contentView.subviews.forEach { childView in
    childView.removeFromSuperview()
}
```

2020-09-05 00:50 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +        case CategoryType.meat.rawValue:
ここの実装は改善されていてとてもよいです👍
もう一歩レベルが上の実装として、enum propertyを使用すると更に可読性が良いので活用してみましょう💁‍♂️

```swift
    enum CategoryType: Int{
        case meat
        case fish
        ...
        
        var name: String {
            switch self {
            case .meat: return R.string.categoryType.meat()
            case .fish: return R.string.categoryType.fish()
            ...
            }
        }
    }

// USAGE: CategoryType.meat.name → 肉
// e.g. categoryName = CategoryType(rawValue: indexPath.row).name → type毎のnameが自動で割り当てられる
```

2020-09-05 00:50 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/CategoryCollectionViewController.swift
> +    enum CategoryType:Int{
細かいですが、コロンの後には半角スペースを入れましょう💁‍♂️

2020-09-05 05:41 UTC, yamataku29 approved these changes
LGTM!🎉

2020-09-05 06:10 UTC, merged