APIでレシピ情報取得(レシピカード表示画面)  #6
kusio940/RecommendRecipe pull request #22
Opened 2020-10-15 11:16 UTC by kusio940

## Issue
APIでレシピ情報取得(レシピカード表示画面)  #6

## 変更内容
・UIImageのExtensionを作成し、非同期で画像取得
・OSSのswiftyJson導入
・楽天レシピAPIでカテゴリごとのレシピ情報を取得
・json解析し、レシピ名、画像、説明を表示

## レビュー依頼内容
・RecipeCardViewController.swiftのコードレビュー
・RakutenRecipeApiClient.swiftのコードレビュー
・大量のenumを作る必要があったためRecipeCardViewController+Extension.swiftで作成したが、問題がないか
・RecipeData.swiftとしてデータモデルを作成したことは問題がないか

2020-10-15 11:59 UTC, yamataku29 requested changes
Extensionの実装は中々頑張りましたね😅
内容自体は問題ないと思うので、この方針でいきましょう👍

後他にもいくつか細かい部分のコメント入れました💡

2020-10-15 11:59 UTC, yamataku29 commented on RecommendRecipe/Models/RakutenRecipeApiClient.swift
> +                        let json = try JSON(data: data)
JSONデータのDecodeはCodableを使って上げるとここのネストが深い処理は改善できそうですね💁‍♂️
https://qiita.com/Mt-Hodaka/items/d14447a429948a3fb28c
https://qiita.com/_ha1f/items/bf1aad5ea3e927f59f9d

2020-10-15 11:59 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +    func updateRecipeCard(){
メソッドの閉じ括弧の後ろは半角スペースを開けましょう💁‍♂️

2020-10-15 11:59 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +        guard let categoryType = self.navigationItem.title else{ return }
このelseの後ろも半角スペースがほしいですね。

2020-10-15 11:59 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +    func generateRandamNumber(categoryType: String, exclusionNumber: Int) -> Int{
ここのIntの後ろの半角スペースが欲しいですね👏

2020-10-15 13:02 UTC, kusio940 commented on RecommendRecipe/Models/RakutenRecipeApiClient.swift
> +                        let json = try JSON(data: data)
SwiftyJSONではなく、Codableでjson解析をした方がよいというご指摘でしょうか。
Codableによるネストの改善があまり理解ができていません。。。

2020-10-15 13:13 UTC, kusio940 commented
コードにおいて以下の点をお聞きしたく思います。
・RakutenRecipeApiClient/fetchCategoryRanking にて、semaphoreでAPIからの値が同期的にとれるように処理をしていますが、特に問題ないでしょうか（他に良いやり方がないでしょうか。）
・RecipeCardViewController/updateRecipeCard　にて、非同期処理で通信を行っている箇所、及び以下のようにインジケータを止める処理を無理やり行っていると感じているのすが、特に問題はないでしょうか。
`                guard let categoryID = RakutenRecipeCategoryId(rawValue: categoryType)?.getCategoryId(smallCategoryNumber: 0)
                else{
                    DispatchQueue.main.async {
                        self.stopIndicator(activityIndicatorView: self.activityIndicator)
                    }
                    return
                }`

2020-10-17 04:21 UTC, yamataku29 commented on RecommendRecipe/Models/RakutenRecipeApiClient.swift
> +                        let json = try JSON(data: data)
今はSwiftyJSONを使っているのですね💡
であれば既存の方法でも問題はありません🙆‍♂️

2020-10-17 04:28 UTC, yamataku29 commented
@kusio940 
> ・RakutenRecipeApiClient/fetchCategoryRanking にて、semaphoreでAPIからの値が同期的にとれるように処理をしていますが、特に問題ないでしょうか（他に良いやり方がないでしょうか。）

ここは改善の余地はありそうですね👀
API通信処理というのは、本来的に同期処理ができない(基本的な概念として全て非同期になる)ので、それを前提として考える必要があります💁‍♂️
通常、API通信(=非同期処理)をした結果を受け取りたい場合、受け取った結果をクロージャーの引数として渡すのが王道だったりします💡
クロージャーについては下記の記事などがとても丁寧に書かれているのですが、これを参考に実装をチャレンジすることができそうですか？

https://qiita.com/yimajo/items/32a5209bd73580d283a1#%E3%82%AF%E3%83%AD%E3%83%BC%E3%82%B8%E3%83%A3%E3%82%92%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%AB%E6%B8%A1%E3%81%99%E6%96%B9%E6%B3%95

今回の場合だと、`fetchCategoryRanking`に`completion`などのクロージャー引数を渡すイメージですね👌

> ・RecipeCardViewController/updateRecipeCard　にて、非同期処理で通信を行っている箇所、及び以下のようにインジケータを止める処理を無理やり行っていると感じているのすが、特に問題はないでしょうか。
guard let categoryID = RakutenRecipeCategoryId(rawValue: categoryType)?.getCategoryId(smallCategoryNumber: 0) else{ DispatchQueue.main.async { self.stopIndicator(activityIndicatorView: self.activityIndicator) } return }

ここも上述したクロージャーを引数として渡すメソッドを別途作成して上げるとよさそうですね😌
下記の記事などは特にAPI通信時にクロージャーを用いているパターンなので、こちらも参考になるかも知れません。

https://qiita.com/kawano108/items/2e00155e157773375007

2020-10-18 05:45 UTC, kusio940 commented
ご指摘いただいたクロージャーでの実装を行いました。
コードレビューお願いします。

2020-10-18 10:27 UTC, yamataku29 approved these changes
うん！非同期処理らしい書き方になりましたね☺️
良いと思います！LGTM🙆‍♂️✨

2020-10-18 12:03 UTC, merged

2020-10-18 12:03 UTC, kusio940 commented
マージしました！
ありがとうございます