feature/#9
kusio940/RecommendRecipe pull request #24
Opened 2020-10-19 11:46 UTC by kusio940

## Issue
お気に入りボタン及びDB実装(レシピカード表示画面)

## 変更内容
・OSSのRealm導入
・RecipeCardViewController内にお気に入り追加ボタン実装
・日付取得用のDate+Extension実装
・RakutenRecipeApiClientにてrecipeIdがintでなくstringで取得していたミスを修正
・RealmManager実装
・realmで使うFavoriteを実装

## レビュー依頼内容
・RecipeCardViewController.swiftのコードレビュー
・RealmManager内によくない書き方をしているコードがないか
・Date+Extension及び、それを利用している箇所（RealmManager：30）の書き方に違和感がないか

2020-10-20 00:12 UTC, yamataku29 reviewed
コメントしました💡

2020-10-20 00:12 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +        if(recipeDataArray.isEmpty){
ここは敢えて`firstCount`のインスタンス化しなくても`currentCount`をそのまま使えば同じ結果になる気もするのですが、そうではないですかね？🤔

```swift
func updateCardCountLabel() {
    let currentCount = kolodaView.currentCardIndex + 1
    cardCountLabel.text = String(currentCount) + "/" + String(recipeCardCount)    
}
```

2020-10-20 00:12 UTC, yamataku29 commented on RecommendRecipe/Extensions/Date+Extension.swift
> +    }
ここはグローバルなExtensionであって、RecipeCardViewControllerのためだけに存在する訳ではなく他のクラスからも参照される可能性を考えるのならば、dateFormatは外部から指定できる方が汎用性は高そうです💁‍♂️

```swift
func getCurrentTime(format: String = "yMMMdHmsSSS") -> String {
    let now = Date()
    let dateFormatter = DateFormatter()
    // DateFormatter を使用して書式とロケールを指定する
    dateFormatter.dateFormat = DateFormatter.dateFormat(fromTemplate: format, options: 0, locale: Locale(identifier: "ja_JP"))
    return dateFormatter.string(from: now)
}
```

2020-10-20 00:12 UTC, yamataku29 commented on RecommendRecipe/Models/RakutenRecipeApiClient.swift
> +                            if(recipeIdString == "-1") {
このマジックナンバーも定数化しましょう💡

2020-10-20 00:12 UTC, yamataku29 commented on RecommendRecipe/Models/Realm/RealmManager.swift
> +    let realmFilePath =  NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0] + "/default.realm"
`[0]`は`.first`プロパティで置き換えができそうですね👏

2020-10-20 00:12 UTC, yamataku29 commented on RecommendRecipe/Models/Realm/RealmManager.swift
> +    }
RealmManagerは恐らく汎用性の高いクラスだと思いますので、特定のモデルの読み書きを考慮しなくてはならない設計は好ましくないですね🤔

というのも、今後Realmで管理するモデルが増えた場合、その増えたモデル分だけwriteやdeleteなどのメソッドを生やさないとイケないので、そうするとこのManagerクラスメンテナンスが大変になってしまいます😨

僕も個人アプリでRealmManagerクラスを活用しているので、参考として記載しておきますね💁‍♂️

```swift
class RealmManager {
    typealias Item = Object
    var database: Realm
    var seedData: Realm
    var dummyData: Realm
    static let shared = RealmManager()
    static private let schemaVersion: UInt64 = 5
    
    init() {
        database = try! Realm()
        let searchDataUrl = Bundle.main.url(forResource: "seed", withExtension: "realm")
        let searchDataConfig = Realm.Configuration(fileURL: searchDataUrl, readOnly: true)
        seedData = try! Realm(configuration: searchDataConfig)
        let dummyDataUrl = Bundle.main.url(forResource: "dummy", withExtension: "realm")
        let dummyDataConfig = Realm.Configuration(fileURL: dummyDataUrl, readOnly: true)
        dummyData = try! Realm(configuration: dummyDataConfig)
    }
    
    func commitWriteIfNeeded() {
        if database.isInWriteTransaction {
            try! database.commitWrite()
        }
    }
    
    func beginWriteIfNeeded() {
        guard !database.isInWriteTransaction else { return }
        database.beginWrite()
    }
    
    func cancelWriteIfNeeded() {
        if database.isInWriteTransaction {
            database.cancelWrite()
        }
    }
    
    func getObject(type: Object.Type) -> Results<Object> {
        return database.objects(type.self)
    }
    
    func getData() -> Results<Item> {
        let results = database.objects(Item.self)
        return results
    }
    
    func addData(object: Item, update: Realm.UpdatePolicy = .error) {
        if RealmManager.shared.database.isInWriteTransaction {
            RealmManager.shared.database.cancelWrite()
        }
        try! database.write {
            database.add(object, update: update)
        }
    }
    
    func deleteAppData() {
        try! database.write {
            database.deleteAll()
        }
    }
    
    func deleteData(object: Item) {
        try! database.write {
            database.delete(object)
        }
    }
    
    static var fileUrl: String {
        return Realm.Configuration.defaultConfiguration.fileURL?.absoluteString ?? "Not found"
    }
    
    class func dataMigrate() {
        // Changed the schemaVersion of Realm for data migration
        Realm.Configuration.defaultConfiguration = Realm
            .Configuration(schemaVersion: schemaVersion,
                           migrationBlock: { migration, oldSchemaVersion in
                            if (oldSchemaVersion < 1) {
                                migration.enumerateObjects(ofType: MealRecord.className()) { oldObject, newObject in
                                    let adjustRate = oldObject!["adjustRate"] as! Int
                                    if adjustRate == .zero {
                                        newObject!["adjustRate"] = 100
                                    }
                                }
                            }
                            if (oldSchemaVersion < 2) {
                                migration.enumerateObjects(ofType: MealRecord.className()) { oldObject, newObject in
                                    let protein = oldObject!["protein"] as! NSNumber
                                    let fat = oldObject!["fat"] as! NSNumber
                                    let carbohydrate = oldObject!["carbohydrate"] as! NSNumber
                                    let calorie = oldObject!["calorie"] as! Int
                                    newObject!["protein"] = Double(truncating: protein)
                                    newObject!["fat"] = Double(truncating: fat)
                                    newObject!["carbohydrate"] = Double(truncating: carbohydrate)
                                    newObject!["calorie"] = Double(calorie)
                                }
                                migration.enumerateObjects(ofType: FavoriteFood.className()) { oldObject, newObject in
                                    let protein = oldObject!["protein"] as! NSNumber
                                    let fat = oldObject!["fat"] as! NSNumber
                                    let carbohydrate = oldObject!["carbohydrate"] as! NSNumber
                                    let calorie = oldObject!["calorie"] as! NSNumber
                                    newObject!["protein"] = Double(truncating: protein)
                                    newObject!["fat"] = Double(truncating: fat)
                                    newObject!["carbohydrate"] = Double(truncating: carbohydrate)
                                    newObject!["calorie"] = Double(truncating: calorie)
                                }
                            }
                            if (oldSchemaVersion < 3) {
                                migration.enumerateObjects(ofType: ExerciseRecord.className()) { oldObject, newObject in
                                    let exerciseWeight = oldObject!["exerciseWeight"] as! Int
                                    newObject!["exerciseWeight"] = Double(exerciseWeight)
                                }
                                migration.enumerateObjects(ofType: FavoriteExercise.className()) { oldObject, newObject in
                                    let exerciseWeight = oldObject!["exerciseWeight"] as! Int
                                    newObject!["exerciseWeight"] = Double(exerciseWeight)
                                }
                            }
                            if (oldSchemaVersion < 4) {
                                migration.enumerateObjects(ofType: BodyMakeSetting.className()) { oldObject, newObject in
                                    newObject!["objectId"] = UUID().uuidString
                                }
                            }
            })
    }
}
```

```swift
// Usage

// Get
let record = RealmManager.shared.getObject(type: MealRecord.self)

// Get with filter
let result = RealmManager.shared.getObject(type: MealRecord.self)
            .filter("ingestionTime BETWEEN {%@, %@}", startPoint, endPoint).array as? [MealRecord] ?? []

// Save record
let favoriteFood = FavoriteFood()
RealmManager.shared.addData(object: favoriteFood)

// Delete record
let favoriteFood = RealmManager.shared.getObject(type: FavoriteFood.self).filter("objectId = %@", food.objectId).array?.first as? FavoriteFood
RealmManager.shared.deleteData(object: favoriteFood)
```

2020-10-20 13:00 UTC, kusio940 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +        if(recipeDataArray.isEmpty){
レシピカードが更新され、再表示されるまでcurrentCardIndexが保持されているようでした。
そのため、currentCountをそのまま使用すると1/8と再表記されなかったので、現在のようなコードとなりました。

2020-10-20 13:55 UTC, kusio940 commented
修正を行いました。
再度レビューお願いいたします。

2020-10-21 11:15 UTC, yamataku29 requested changes
細かい点についてコメントしました🙆‍♂️

2020-10-21 11:15 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +        let firstIndex:Int = .zero
コロンの後はスペースを空けましょう💁‍♂️

2020-10-21 11:15 UTC, yamataku29 commented on RecommendRecipe/CategorySelectView/RecipeCardView/RecipeCardViewController.swift
> +        if(recipeDataArray.count != recipeCardCount){
ここもifと閉じ括弧の後ろは半角スペースを空けましょう💁‍♂️

2020-10-21 11:15 UTC, yamataku29 commented on RecommendRecipe/Models/RakutenRecipeApiClient.swift
> +                            }
ここは三項演算子を使った方がシンプルにかけそうですね💡
```swift 
var recipeIdString = recipeId == nil ? "" : String(recipeId!)
```

2020-10-22 01:18 UTC, yamataku29 approved these changes
良さそうです！
LGTM🙆‍♂️🎉

2020-10-22 08:34 UTC, kusio940 commented
ありがとうございます。
マージします。

2020-10-22 08:35 UTC, merged